import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F2F2F2' },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#756EF3',
        padding: 30,
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
    },
    headerTitle: {
        flex: 1,
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'start',
        paddingLeft: 18,
        paddingTop: 18,
    },
    iconMargin: { marginLeft: 16, paddingTop: 18 },
    statusSummary: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        padding: 16,
        marginVertical: 16,
        marginHorizontal: 17,
        backgroundColor: '#FFF',
        borderRadius: 12,
    },
    statusItem: { alignItems: 'center' },
    count: { fontSize: 24, fontWeight: '600' },
    statusTextBlack: { color: '#859399', fontSize: 14, textAlign: 'center' },
    searchContainer: {
        borderColor: '#859399',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 16,
        marginHorizontal: 17,
        marginBottom: 16,
    },
    searchInput: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: '#FFF',
        color: '#333',
    },
    iconContainer: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 12,
        marginLeft: 4,
    },
    listContainer: { paddingBottom: 16 },
    vehicleItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    Row: {   
        width:"60%" ,    
        flexDirection: 'row',    
    },
    Column:{
        paddingLeft:17,
        flexDirection: 'column', 
    },
    newTest:{
        paddingTop: 25,
        paddingLeft: 40,        
        flexDirection: 'column', 
    },
    expanded: {
        flexDirection: 'column',
        alignItems: 'start',
        backgroundColor: '#FFF',
        marginHorizontal: 16,
        marginBottom: 16,
        padding: 12,
        borderRadius: 12,
    },
    statusIndicator: { width: 4, marginLeft: 20, marginRight: 14 },
    majorIssueContainer: {
        position: 'absolute',
        left: -50,
        top: 10,
        backgroundColor: '#F3F3F3',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    majorIssueText: { color: '#6F6EF3', fontWeight: 'bold' },
    vehicleInfo: { flex: 1 },
    vehicleNumber: { fontSize: 22, fontWeight: '600' },
    vehicleId: { fontSize: 14, color: '#888' },
    vehicleStatus: {
        flexDirection: 'column',
        height: 65,
        width: 72,
        alignItems: 'center',
    },
    statusBox: {
        height: 65,
        width: 72,
        borderRadius: 10,
        marginBottom: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    locationText: {
        color: '#32ADE6', 
      },
    statusText: {
        fontSize: 12,
        textAlign: 'center',
        marginBottom: 4,
        color: 'white',
        fontWeight: '700',
    },
    divider: {
        height: 1,         
        backgroundColor: '#ccc', 
        marginVertical: 8,  
      },
    expandedDetails: {
        marginTop: 10,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
        width: '100%',
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',        
        paddingLeft: 20,
    },
    detailLabel: { color: '#757575', fontSize: 14 ,paddingTop:20},
    detailValue: { color: '#000', fontSize: 14, fontWeight: 'bold' ,alignItems:"center"},
    detailsButton: {
        marginTop: 10,
        backgroundColor: 'black',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        alignItems: 'center',
    },
    detailsButtonText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
    urlPurpleText: {
        color: '#6F6EF3',
        fontWeight: '500',
        fontSize: 14,
        textDecorationLine: 'underline',
    },
    batteryText: { marginLeft: 4, color: '#888' },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: { width: 200, backgroundColor: 'white', borderRadius: 8, padding: 10 },
    modalOption: { paddingVertical: 10, alignItems: 'center' },
    modalOptionText: { fontSize: 16 },
    imageIconContainer: {
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        height: 80,
        paddingRight: 10,
    },
    imageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: 50,
        paddingTop: 20,
        paddingRight: 8,
    },
    image: { width: 20, height: 20, marginBottom: 5 },
    iconTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    smallText:{
        fontSize:12,
    },
    containerTable: {
        flexDirection: 'column',
        padding: 16,
      },
      rowTable: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 2,       
      },
    iconText: { fontSize: 10, textAlign: 'center', paddingLeft: 10 },
});

export default styles;
